export const appIdNameMapByCategory: Record<string, Record<string, string>> = {
	dev: {
		'code': 'Visual Studio Code',
		'Code': 'Visual Studio Code',
		'code-url-handler': 'Visual Studio Code - URL Handler',
		'micro': 'Micro',
		'org.gnome.Meld': 'Meld',
		'org.kde.kate': 'Kate 编辑器',
		'kate': 'Kate 编辑器',
		'org.kde.kwrite': 'KWrite 记事本',
		'kwrite': 'KWrite 记事本',
		'vim': 'Vim',
	},
	games: {
		'Reload': '女神异闻录３ Reload',
		'steam': 'Steam',
		'the-honkers-railway-launcher': '崩坏：星穹铁道（启动器）',
		'xmcl': 'XMCL Minecraft 启动器',
	},
	media: {
		'com.example.piliplus': 'PiliPlus',
		'echomusic': 'EchoMusic',
		'mpv': 'mpv 媒体播放器',
		'org.pulseaudio.pavucontrol': '音量控制',
		'wps-office-pdf': 'WPS PDF',
		'wpspdf': 'WPS PDF',
	},
	network: {
		'Clash Verge': 'Clash Verge',
		'avahi-discover': 'Avahi Zeroconf 浏览器',
		'bluetooth-sendto': '蓝牙传送',
		'bssh': 'Avahi SSH 服务器的浏览器',
		'bvnc': 'Avahi VNC 服务器的浏览器',
		'clash-verge': 'Clash Verge',
		'clash-verge-handler': 'Clash Verge',
	},
	office: {
		'obsidian': 'Obsidian',
		'wps-office-et': 'WPS 表格',
		'et': 'WPS 表格',
		'wps-office-prometheus': 'WPS Office',
		'wpsoffice': 'WPS Office',
		'wps-office-wpp': 'WPS 演示',
		'wpp': 'WPS 演示',
		'wps-office-wps': 'WPS 文字',
		'wps': 'WPS 文字',
	},
	social: {
		'Element': 'Element',
		'QQ': 'QQ',
		'io.element.Element': 'Element',
		'qq': 'QQ',
	},
	system: {
		'CherryStudio': 'Cherry Studio',
		'MotrixNext': 'MotrixNext',
		'btop': 'btop++',
		'cachyos-hello': 'CachyOS Hello',
		'cachyos-pi': 'CachyOS Package Installer',
		'cherry-studio': 'Cherry Studio',
		'cherrystudio-url-handler': 'Cherry Studio',
		'dolphin': 'Dolphin 文件管理器',
		'firefox': 'Firefox',
		'kbd-layout-viewer5': '键盘布局测试器',
		'kcm_fcitx5': '输入法',
		'kcm_trash': '回收站',
		'kcm_webshortcuts': '网页搜索关键词',
		'motrix-next': 'MotrixNext',
		'nautilus-autorun-software': '运行软件',
		'org.cachyos.KernelManager': 'CachyOS Kernel Manager',
		'org.cachyos.hello': 'CachyOS Hello',
		'org.cachyos.scx-manager': 'SchedExt GUI Manager',
		'org.gnome.ColorProfileViewer': '配置查看器',
		'org.gnome.Extensions': '扩展',
		'org.gnome.Nautilus': '文件',
		'org.gnome.OnlineAccounts.OAuth2': 'GNOME OAuth2 Handler',
		'org.gnome.Ptyxis': 'Ptyxis',
		'org.gnome.Settings': '设置',
		'org.gnome.Shell.Extensions': '扩展',
		'org.gnome.Tecla': 'Tecla',
		'org.gnome.Zenity': 'Zenity',
		'org.gnupg.pinentry-qt': 'Pinentry',
		'org.gnupg.pinentry-qt5': 'Pinentry',
		'org.kde.dolphin': 'Dolphin 文件管理器',
		'org.kde.kiod6': 'KIO',
		'org.kde.knewstuff-dialog6': 'KNewStuff 对话框',
		'org.kde.ksecretd': 'KDE 密码库服务',
		'shelly': 'Shelly',
		'thunar': 'Thunar 文件管理器',
		'thunar-bulk-rename': '批量重命名',
		'thunar-settings': 'Thunar 首选项',
		'winetricks': 'Winetricks',
		'zen': 'Zen Browser',
	},
	settings: {
		'gnome-about-panel': '关于',
		'gnome-applications-panel': '应用',
		'gnome-background-panel': '外观',
		'gnome-bluetooth-panel': '蓝牙',
		'gnome-color-panel': '色彩管理',
		'gnome-datetime-panel': '日期和时间',
		'gnome-display-panel': '显示器',
		'gnome-keyboard-panel': '键盘',
		'gnome-mouse-panel': '鼠标和触摸板',
		'gnome-multitasking-panel': '多任务',
		'gnome-network-panel': '网络',
		'gnome-notifications-panel': '通知',
		'gnome-online-accounts-panel': '在线账号',
		'gnome-power-panel': '电源',
		'gnome-printers-panel': '打印机',
		'gnome-privacy-panel': '隐私与安全',
		'gnome-region-panel': '区域与语言',
		'gnome-search-panel': '搜索',
		'gnome-sharing-panel': '共享',
		'gnome-sound-panel': '声音',
		'gnome-system-panel': '系统',
		'gnome-universal-access-panel': '无障碍',
		'gnome-users-panel': '用户',
		'gnome-wacom-panel': '数位板',
		'gnome-wellbeing-panel': '健康',
		'gnome-wifi-panel': 'Wi-Fi',
		'gnome-wwan-panel': '移动网络',
	},
}

export const appIdNameMap: Record<string, string> = {
	...appIdNameMapByCategory.dev,
	...appIdNameMapByCategory.games,
	...appIdNameMapByCategory.media,
	...appIdNameMapByCategory.network,
	...appIdNameMapByCategory.office,
	...appIdNameMapByCategory.social,
	...appIdNameMapByCategory.system,
	...appIdNameMapByCategory.settings,
}
