$ErrorActionPreference = 'Stop'

# Compare the Astro route set against the FROZEN Nuxt baseline.
#
# NOTE: this script must stay ASCII-only. Windows PowerShell 5.1 reads BOM-less
# .ps1 files using the system ANSI code page; non-ASCII bytes in comments get
# mangled and can swallow the following newline, silently breaking later lines.
#
# NOTE: both paths resolve from $PSScriptRoot, not the process CWD. This script
# used to read `..\baseline-urls.txt`, a file that has never existed anywhere in
# the repository -- so it died on its first statement and reported exit 1, which
# is indistinguishable from "the URL sets differ" if you only read the exit code.
# The list is now generated by scripts/freeze-baseline.mjs into baseline/nuxt/.

$siteRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$base = (Resolve-Path (Join-Path $siteRoot 'baseline\nuxt\urls.txt')).Path
$dist = Join-Path $siteRoot 'dist'

# Non-content routes excluded from the gate, per side:
#   baseline /favicon.ico : 308 redirect stub emitted by Nuxt routeRules.
#                          Astro handles redirects via astro.config redirects instead.
#   astro     /probe      : Phase 2 mechanism probe page (component map / named slot / KaTeX).
#                          Deleted during cleanup.
# Exclusion lists are now empty on both sides: every baseline route has an
# Astro counterpart, including /favicon.ico (a meta-refresh stub emitted by
# src/pages/favicon.ico.astro, byte-identical to the Nuxt one).
$excludeFromBaseline = @()
$excludeFromAstro = @()

function Normalize-Url([string]$raw) {
	# Strip a trailing slash, but never let the site root collapse to an empty
	# string: '' would be dropped by the blank filter below and the homepage
	# would silently vanish from the comparison.
	$t = $raw.Trim()
	if ($t -eq '' -or $t -eq '/') { return '/' }
	return $t.TrimEnd('/')
}

$baseline = Get-Content $base -Encoding UTF8 |
	ForEach-Object { Normalize-Url $_ } |
	Where-Object { $_ -ne '' -and $excludeFromBaseline -notcontains $_ } |
	Sort-Object -Unique

$astro = Get-ChildItem $dist -Recurse -File -Filter *.html |
	Where-Object { $_.Name -notin @('200.html', '404.html') } |
	ForEach-Object {
		Normalize-Url ($_.FullName.Substring($dist.Length).Replace('\', '/') -replace '/index\.html$', '/' -replace '\.html$', '')
	} |
	Where-Object { $_ -ne '' -and $excludeFromAstro -notcontains $_ } |
	Sort-Object -Unique

"baseline pages : $($baseline.Count)"
"astro pages    : $($astro.Count)"
''

$onlyBaseline = @(Compare-Object $baseline $astro | Where-Object SideIndicator -eq '<=' | ForEach-Object InputObject)
$onlyAstro = @(Compare-Object $baseline $astro | Where-Object SideIndicator -eq '=>' | ForEach-Object InputObject)

if ($onlyBaseline.Count -gt 0) {
	"### ONLY IN NUXT BASELINE ($($onlyBaseline.Count)) - missing in Astro"
	$onlyBaseline | ForEach-Object { "  - $_" }
}
else { '### ONLY IN NUXT BASELINE: none' }
''

if ($onlyAstro.Count -gt 0) {
	"### ONLY IN ASTRO ($($onlyAstro.Count)) - not in baseline"
	$onlyAstro | ForEach-Object { "  + $_" }
}
else { '### ONLY IN ASTRO: none' }
''

"### COMMON: $(@(Compare-Object $baseline $astro -IncludeEqual -ExcludeDifferent).Count)"

$diff = $onlyBaseline.Count + $onlyAstro.Count
''
# An explicit exit code, not just a printed verdict. acceptance.ps1 reads
# $LASTEXITCODE, so a script that prints RESULT: FAIL without exiting non-zero
# is recorded as PASS (findings 85.5: 8 of 12 static gates could not go red).
if ($diff -eq 0) {
	'RESULT: PASS - zero URL diff'
	exit 0
}
"RESULT: DIFF=$diff - review the entries above"
exit 1
